version: '2'
services:
  app:
    build:
      context:  ../../
      dockerfile: docker/release/Dockerfile
    volumes_from:
      - webroot
    links:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.release
      MYSQL_HOST: db
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
      DEBUG: "false"
    command:
      - uwsgi
      - "--socket /var/www/todobackend/todobackend.sock"
      - "--chmod-socket=666"
      - "--module todobackend.wsgi"
      - "--master"
      - "--die-on-term"
  webroot:
    build:
      context:  ../../
      dockerfile: docker/release/Dockerfile
    volumes:
      - /var/www/todobackend
    entrypoint: "true"
  nginx:
    image: nginx
    links:
      - app
    volumes:
      - ./todobackend.conf:/etc/nginx/conf.d/todobackend.conf
    ports:
      - 8000:8000
    volumes_from:
      - "webroot"
  test:
    image: storager/todobackend-specs
    links:
      - nginx
    environment:
      URL: http://nginx:8000/todos
      JUNIT_REPORT_PATH: /report/acceptance.xml
      JUNIT_REPORT_STACK: 1
    command: 
      - "--timeout"
      - "20000"
      - "--reporter mocha-jenkins-reporter"

  db:
    image: storager/mysql:5.7
    hostname: db
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todobackend
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
  agent:
    image: storager/ansible2
    volumes:
      - ../../ansible/probe.yml:/ansible/site.yml
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
