version: '2'
services:
  app:
    build:
      context:  ../../
      dockerfile: docker/release/Dockerfile
    volumes:
      - webroot:/var/www/todobackend
    links:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.release
      MYSQL_HOST: db
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
      DEBUG: "false"
    command:
      - uwsgi
      - "--socket /var/www/todobackend/todobackend.sock"
      - "--chmod-socket=666"
      - "--module todobackend.wsgi"
      - "--master"
      - "--die-on-term"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - app
    ports:
      - 8000:8000
    volumes:
      - webroot:/var/www/todobackend
  test:
    image: storager/todobackend-specs
    links:
      - nginx
    environment:
      URL: http://nginx:8000/todos
      JUNIT_REPORT_PATH: /reports/acceptance.xml
      JUNIT_REPORT_STACK: 1
    command: 
      - "--reporter"
      - "mocha-jenkins-reporter"
      - "--timeout"
      - "20000"

  db:
    image: storager/mysql:5.7
    hostname: db
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todobackend
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
  agent:
    image: storager/ansible2
    command: ["probe.yml"]
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
volumes:
  webroot: {}
